services:
  ticketing:
    container_name: tsi-ticketing
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - AWS_REGION=<YOUR_AWS_REGION>
      - AWS_ACCESS_KEY_ID=<YOUR_AWS_ACCESS_KEY_ID>
      - AWS_SECRET_ACCESS_KEY=<YOUR_AWS_SECRET>
      - NGROK_TOKEN=<YOUR_NGROK_TOKEN>