services:
  ticketing:
    container_name: tsi-ticketing
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - AWS_REGION=<YOUR_AWS_REGION>
      - AWS_ACCESS_KEY_ID=<YOUR_AWS_ACCESS_KEY_ID>
      - AWS_SECRET_ACCESS_KEY=<YOUR_AWS_SECRET>
      - NGROK_DOMAIN=<YOUR_NGROK_DOMAIN>
      - NGROK_TOKEN=<YOUR_NGROK_TOKEN>
    volumes:
      - data:/app/data
volumes:
  data: