apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: ticketing
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: jalijeff/kube-tsi-ticketing:latest
          ports:
            - containerPort: 5000
          env:
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-region
                  key: data
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: data
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: data